### ISSUE TITLE
Missing workflow for automatic document update

### ISSUE THREAD

**Issue by jiweiqi** [GenXProject/GenX#1]
Looks like a workflow file that automatically updating and deploys the document website is missing. Something like [this example](https://github.com/DENG-MIT/Arrhenius.jl/blob/main/.github/workflows/Documentation.yml). I may be able to help with that if needed.

Update: maybe it is not necessary.

**Comment by sambuddhac** [comment]
We would highly appreciate the help. However, is this file related to the automatic build (through TravisCI or GitHub Actions)? If so, we haven't actually done that yet. We are implementing open-source non-commercial free solvers first in order to be able to do the continuous integration and automated build. But, please inform me more on how to fix the workflow issue.

**Comment by jiweiqi** [comment]
Yes, the one in my head is automatic Github actions, that rebuild the document website every time it detects changes. Alternatively, the website can be manually updated every time. Looks like this is not an emerging task and it can be done in the future.

**Comment by sambuddhac** [comment]
Hi Jiaqi, I have made a bunch of updates on the GenX. Would you please go through your issues and PR once to check if now they work fine? If yes, I will go ahead and close them. If there are some new issues and PR, please feel free to submit. Although I might suggest holding back a couple more days. We will be doing the grand release tomorrow or on Wednesday. Just polishing up a few small pieces.

**Comment by jiweiqi** [comment]
Great. I think the issues I have opened are all resolved. I will close them now.
