### ISSUE TITLE
1st run of Genx 

### ISSUE THREAD

**Issue by codedabacus** [GenXProject/GenX#205]
I am trying to get GenX running for the 1st time and going through the instructions, but my result shows an empty project after I run "instantiate" and check status. I have attached a snapshot here. Thanks for helping out and for your time.
![GenX package_empty project](https://user-images.githubusercontent.com/96933072/167454094-e8df682d-c742-4ab9-808d-d563adc72926.JPG)

**Comment by sambuddhac** [comment]
First type *activate .* and then *instantiate* ... then check the status. It should show all the packages installed.

**Comment by sambuddhac** [comment]
Slight correction: That's activate followed by a space and then a dot (".") .... Rest of the steps are same. Also a slightly easier way to type that first command might be julia --project="GenX"

**Comment by codedabacus** [comment]
Thank you so much!
It works. The only error is the SCIP installation. Will this be an immediate problem running the example folders?
![GenX status](https://user-images.githubusercontent.com/96933072/167460875-45a72745-857b-434b-8755-be89274ecc92.JPG)

**Comment by sambuddhac** [comment]
We, unfortunately, have been having issues with the SCIP solver on Windows machines. One thing to make sure when running on Windows is to separately download and install SCIP solver from their webpage (SCIP on Windows machines works the same as commercial solvers like CPLEX or Gurobi in this respect). Otherwise, I would suggest using Clp or Cbc (Based on whether you set the UCommit flag o GenX_settings.yml to 0/2 or to 1 respectively). If you are comfortable at changing environment variables on a Windows machine (Myself, comfortable with only Linux or Mac machines) and installing and linking dynamically linked libraries, then you can follow those instructions above to see if SCIP works. If you are successful, please let me know, in which case, I will ask you to contribute some sections of the doc pages. Cheers !!!

**Comment by xuqingyu** [comment]
@sambuddhac should we simply not include SCIP in GenX as default? I.e., treat it the same as CPLEX and Gurobi commenting out the related code?

**Comment by sambuddhac** [comment]
PR #218 should address this.

**Comment by sambuddhac** [comment]
@codedabacus , please let me know if this issue is now resolved when you try running GenX v0.3.1 from the main branch (or, from the develop branch, that's intended to be the next version release). If it's fixed, I will close the issue. Please bear in mind that we made significant changes as to how to run GenX and lease read the README and/or doc pages to see the instructions on how to run.

**Comment by codedabacus** [comment]
Yes, it worked for me. Thanks.

**Comment by sambuddhac** [comment]
Ok thanks. Then, I am closing it as resolved.
