### ISSUE TITLE
Error running GenX sample

### ISSUE THREAD

**Issue by codedabacus** [GenXProject/GenX#229]
I get an error that says "Permission denied" when I run a sample of GenX, despite getting it to run previously. Has anyone had this issue before? Please advice
![GenX Error_permission denied](https://user-images.githubusercontent.com/96933072/177792702-e26cdc60-3d6c-4638-828c-0bc076ee1519.JPG)

**Comment by sambuddhac** [comment]
@codedabacus , I haven't, seen this error before and wonder why this should happen. I can suggest you to clone or fork a fresh repo and try once again, to see if the error is resolved. Also, please don't delete your existing repo until we figure out the issue. I'll take a look also in the mean time. Please keep me posted.

**Comment by sambuddhac** [comment]
@codedabacus I would also suggest to check if you are at the right folder level by typing pwd() at the julia> prompt and see if  you are within the GenX folder level and to check if you inadvertently changed the folder visibility or permission on your machine for this particular folder or directory.

**Comment by cfe316** [comment]
Hi @sambuddhac @codedabacus 
`include` is a julia command that tries to read the path given as a julia file. Here `include` is being pointed to the `ISONE_Trizone` **folder**. You should instead point it to the `Run.jl` script within that folder,

`include("Example_Systems/RealSystemExample/ISONE_Trizone/Run.jl)`

The permission error is probably because as a folder, it doesn't have "execute" permissions or whatever the Windows equivalent is.

**Comment by sambuddhac** [comment]
Ah ... right ... good catch @cfe316 

Thanks !!!

**Comment by codedabacus** [comment]
@sambuddhac @cfe316 Thanks a bunch. You are so right @cfe316. It is running now.
