### ISSUE TITLE
Input file names are inconsistently case-sensitive depending on operating system

### ISSUE THREAD

**Issue by RuaridhMacd** [GenXProject/GenX#288]
Some users have run into problems when using lower-case names for their input files. This does not usually cause an error on MacOS or Windows, which do not have case-sensitive filesystems, but can cause a variety of problems on Linux, which does. There are also some edge-cases where MacOS and Windows will have issues.

This could be addressed in a variety of ways. Some options are:
- Make it very explicit in the documentation that the file names are case-sensitive
- Add a config file which defines the input filenames, so they're no longer hard-coded.
- Have GenX look for lower case and capitalized versions of the input file names.

**Comment by cfe316** [comment]
The third option here is easiest - it'll look for files in a case insensitive manner and then send an error message if nothing is found. 

This does mean that we won't intentionally be allowed to have both  `Generators.csv` and `generators.csv` but that would be pretty ugly anyway. I can look at this after #294 is pulled since it's somewhat overlapping with that.

**Comment by RuaridhMacd** [comment]
That sounds good. I think just searching for both would be easiest, rather than trying to get fancy based on the OS. If the folder has both it'll be caught early and the error will be easy for the user to digest.

**Comment by sambuddhac** [comment]
This issue is fixed now with the merge of PR#300 onto `Develop` branch.

**Comment by sambuddhac** [comment]
Now fixed on main as well.
