### ISSUE TITLE
Heat rate for NG resources

### ISSUE THREAD

**Issue by fc4uk** [GenXProject/GenX#35]
The heat rate of some NG resources in the "GenX\Example_Systems\RealSystemExample\Generator_data.csv" looks weird. For example, natural gas combustion turbine (R_ID = 7 and 29) has a heat rate of 4.7, which is physically impossible for such a technology. In addition, R_ID = 8 has a heat rate of 0, which is also impossible.

**Comment by sambuddhac** [comment]
@xuqingyu 

I just referred you.

**Comment by sambuddhac** [comment]
This is explanation from @xuqingyu 

This issue is PGs known problem.
4.7 is super efficient indeed 72.6% efficiency. It is because the heat rate of pg is calculated by: EIA reported fuel consumption/EIAs total generation
If there is some data issue during this step (record is wrong), then weird thing happens. We should suggest a reasonable heat rate on our own, and maybe you can help.

**Comment by fc4uk** [comment]
Thanks that makes sense.

Suggestions for PG: filter the generators that have unreasonable heat rate.
For example, the natural gas combined cycle can achieve efficiencies from 40% - 60%, natural gas combustion turbine can achieve efficiencies from 25-35%, the coal-fired power plants can achieve efficiencies from 25 - 50%. Some old generators might have lower efficiency, but it is physically impossible to achieve extremely high efficiency.
