### ISSUE TITLE
multi stage warning message when setting up GenX linux 

### ISSUE THREAD

**Issue by joshdr83** [GenXProject/GenX#364]
WARNING: Method definition write_multi_stage_settings(AbstractString, Base.Dict{K, V} where V where K) in module GenX at /work2/01714/joshdr/stampede2/GenX/src/multi_stage/write_multi_stage_settings.jl:22 overwritten on the same line (check for duplicate calls to `include`).
 ** incremental compilation may be fatally broken for this module **
┌ Warning: Replacing docs for `GenX.write_multi_stage_settings :: Tuple{AbstractString, Dict}` in module `GenX`
└ @ Base.Docs docs/Docs.jl:240

@sambuddhac

**Comment by cfe316** [comment]
This is a known issue, it's harmless. I believe it will be fixed in the next minor release.On Feb 23, 2023 8:08 PM, Joshua Rhodes ***@***.***> wrote:

WARNING: Method definition write_multi_stage_settings(AbstractString, Base.Dict{K, V} where V where K) in module GenX at /work2/01714/joshdr/stampede2/GenX/src/multi_stage/write_multi_stage_settings.jl:22 overwritten on the same line (check for duplicate calls to include).

** incremental compilation may be fatally broken for this module **

┌ Warning: Replacing docs for GenX.write_multi_stage_settings :: Tuple{AbstractString, Dict} in module GenX

└ @ Base.Docs docs/Docs.jl:240

@sambuddhac

**Comment by joshdr83** [comment]
Thanks -- is there a place to check for is this is a known issue before posting here?

**Comment by cfe316** [comment]
I'm afraid not! This lets us know users' pain points though.On Feb 27, 2023 7:44 AM, Joshua Rhodes ***@***.***> wrote:
Thanks -- is there a place to check for is this is a known issue before posting here?

**Comment by cfe316** [comment]
This is now fixed on `main`; please update to the latest `main` version.
