### ISSUE TITLE
Add checks for avoiding errors with technology FLAGS

### ISSUE THREAD

**Issue by nspatank** [GenXProject/GenX#41]
Example issues:
1. Small hydro technology had no technology flag. As a result, the technology capacity was unconstrained.
2. Settings the THERM and MUST_RUN flags ON for Nuclear produced erroneous results
3. Setting the THERM flag was ON and MUST_RUN flag was OFF for biomass and geothermal technologies produced erroneous results. 
4. Setting the STOR flag for small hydro to 2 instead of 1 produced erroneous results.

**Comment by cfe316** [comment]
I'd like to implement something similar for the Thermal-plant-with-integrated-storage systems (of which fusion is a particular example) So this could probably be addressed there as well. 
For example, fusion needs `THERM = 1` and `FUS=1` and `<thermal storage> =1`. Having `FUS=1` without the other two would be invalid. Having `<thermal storage> = 1` without `THERM=1` would be invalid.

**Comment by cfe316** [comment]
@sambuddhac 

This is the demo code for checking of FLAG type columns.
* Reads the generators dataframe and
* collects a list of issues prints out any issues you might have, then
* raises an error.

This is better than just raising an error when an issue is first found because this way you can correct several errors at once.

https://gist.github.com/cfe316/ce9dab47f87a915da0db58eb7c8ddf13

**Comment by xuqingyu** [comment]
@cfe316 is this merged or if not can you create a PR for this?

**Comment by cfe316** [comment]
I don't have an actually working code for this. The Gist above is just a demo. I would want to chat with you and/or Neha and come up with a list of what flags are actually valid or invalid.

**Comment by sambuddhac** [comment]
This feature doesn't exist currently. I need to create a PR.

**Comment by sambuddhac** [comment]
This will be addressed shortly with the automated unit and integration tests.
