### ISSUE TITLE
Slow results writing when using Cbc solver

### ISSUE THREAD

**Issue by jf-morris** [GenXProject/GenX#45]
When running an example (13 regions, 163 resources, 1 year with 10 representative periods) with Cbc, it took me about 2 hours to write results. I have identified that ternary statements such as the one included below from write_costs() (line 70) take several seconds for each region-resource pair. However when using Clp, results writing is almost instantaneous. I will continue to use Clp for now, but I include this for the group's information. 

tempCFix = tempCFix +
      (y in inputs["STOR_ALL"] ? value.(EP[:eCFixEnergy])[y] : 0) +
      (y in inputs["STOR_ASYMMETRIC"] ? value.(EP[:eCFixCharge])[y] : 0) +
      value.(EP[:eCFix])[y]

**Comment by carhels** [comment]
I'm also having problems with this issue. I have 8 zones and 200+ resources. Writing output takes several hours. The worst affected files are those that write the entire time series for each resource, e.g. write_power.jl. I have been using Clp already, so switching to that solver won't help here. Also, I don't understand why a particular solver would make the results writing slow, which happens when the solution is found.

**Comment by sambuddhac** [comment]
Please use the SCIP solver for the moment to resolve this issue, if you are using free open source solvers. Using Gurobi and CPLEX also works in case you have the licenses. I haven't been able to fix it right for Cbc, been working on it. For now, SCIP works fine. Please use the Dev branch until version 0.2 goes live.

**Comment by sambuddhac** [comment]
Please use SCIP instead of CBC
