### ISSUE TITLE
investment_discharge.jl (Lines 162, 166), invetsment_energy.jl (Lines 127, 131), investment_charge.jl (Lines 127, 131) 

### ISSUE THREAD

**Issue by AshwinSandeep1** [GenXProject/GenX#482]
Shouldn't the conditions be Max_Cap >= 0, Min_Cap >= 0 rather than Max_Cap > 0, Min_Cap > 0 to allow the scenario where 0 capacity needs to be installed?

**Comment by cfe316** [comment]
Hi Ashwin, 

Thanks for bringing this up. Yes, this would probably be clearer.  This is something we're aware of. For now, either `0` or `-1` can be used to indicate no set minimum or maximum capacity. In the future we may change the interpretation of `Max_Cap` so that a `0` indicates that the resource must end at zero capacity. If we did that, then negative numbers `-1` and/or `NaN` would likely be the indicators that no maximum capacity is intended for this resource.

**Comment by AshwinSandeep1** [comment]
Hi Jacob

Thank you for the clarification. All clear.
