### ISSUE TITLE
Error in SmallNewEngland/ThreeZones example

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#53]
I'm having trouble getting the SmallNewEngland/ThreeZones example to work. The other two SmallNewEngland examples do work. I'm running GenX version  b0ae69fe27b1d985f4bdc4c4025735cf12fe39c6 (HEAD, tag: v0.1.0)  using Julia version 1.6.1.
The issue is the same on the most recent `main` commit, 46a495b04061e71f58d31dfc30af1206d3cffde2.

I think the error might be related to missing data? It comes with an error:
Reading Input CSV Files
┌ Warning: thread = 1 warning: only found 14 / 15 columns around data row: 4. Filling remaining columns with `missing`
└ @ CSV ~/.julia/packages/CSV/Zl2ww/src/file.jl:612
Network.csv Successfully Read!
[...]
CSV Files Successfully Read In From /home/jacob/GenX/Example_Systems/SmallNewEngland/ThreeZones/
ERROR: LoadError: MethodError: no method matching rename!(::DataFrames.DataFrame, ::Vector{Any})
Closest candidates are: [...]

in expression starting at /home/jacob/GenX/Example_Systems/SmallNewEngland/ThreeZones/Run.jl:40
I'm using the Clp optimizer.

**Comment by sambuddhac** [comment]
Hi Jacob, 

This issue was caused due to the version upgrade and consequent need to modify the command in the time domain clustering script. It has been resolved. I just tested from main branch. Things seem to be working fine now at my end. Can you once check a test run from the main branch please (please do a git pull before testing)? Let me know if the problem still persists. Otherwise, can you please close the issue?

Thanks

Sam

**Comment by cfe316** [comment]
Can confirm; this has been fixed by the update.
